version: "3.2"
services:
  blackbox:
    image: prom/blackbox-exporter:${BLACKBOX_EXPORTER_TAG}
    ports:
      - 9115:9115
    command:
      - --config.file=/etc/blackbox/blackbox.yml
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
  prometheus:
    image: prom/prometheus:${PROMETHEUS_TAG}
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - blackbox
  grafana:
    image: grafana/grafana:${11.4.0GRAFANA_TAG}
    ports:
      - 3000:3000
    depends_on:
      - prometheus
